### PR TITLE
Use http.Error to also set text/plain content type

### LINKED ISSUE #31: Broken response with nosurf and gzip middleware
Chrome, Firefox and Safari does not seem to like the response for a failed token verification when using a gzip middware. Chrome reports "This webpage is not available ERR_INVALID_RESPONSE".

What seems to cause the problem is `Content-Type: application/x-gzip`. In the example this happens because nosurf failure handler does not set any content type and the gzip middleware sets it to `application/x-gzip` if not set.

Have read parts of the HTTP specs but can't really understand if this is a valid response or not. But most browsers does not like it. Would it make sense to change `nosurf.defaultFailureHandler` to `http.Error(rw, "", http.StatusBadRequest)` instead which will set the content type to `text/plain; charset=utf-8`?

```go
package main

import (
	"net/http"

	"github.com/codegangsta/negroni"
	"github.com/phyber/negroni-gzip/gzip"
)

func main() {
	n := negroni.New()
	n.Use(gzip.Gzip(gzip.DefaultCompression))
	n.UseHandlerFunc(func(rw http.ResponseWriter, r *http.Request) {
		// simulate nosurf.defaultFailureHandler
		rw.WriteHeader(http.StatusBadRequest)
	})
	http.ListenAndServe(":3001", n)
}
```

Or is this a bug in the gzip middleware? it should not have a fallback content type (`Content-Encoding: gzip` is enough)?

### PR DESCRIPTION
**Pull request by wader**
Fixes #31

### CODE REVIEW

File: testutils_test.go [hunk 1]
```diff
@@ -40,7 +40,7 @@ func correctReason(t *testing.T, reason error) http.Handler {
 				" but it failed with the reason %#v", reason, got)
 		}
 		// Writes the default failure code
-		w.WriteHeader(FailureCode)
+		http.Error(w, "", FailureCode)
```
Comment (wader) [inline testutils_test.go]: This is a bit weird. Test is not really using the default error handler

Comment (justinas) [inline testutils_test.go]: This one is only used to check for the correct reason of failure in tests. I guess it could fall back on `defaultFailureHandler`.

**Comment by justinas** [comment]
Thanks!

**Comment by wader** [comment]
Nice, thanks for nosurf!
